import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';
import { useAuth } from '../auth-context';

interface MatchReason { criterion: string; points: number; detail: string }
interface MatchRow {
  id: string; status: string; score: number; eligible: boolean; reasons: MatchReason[];
  ngo: { id: string; name: string; city: string | null; isActive: boolean; acceptedCategories: string[] };
}
interface Assessment { id: string; foodDescription: string; quantityKg: number; reason: string | null; createdAt: string }
interface TimelineEv { at: string; action: string; metadata: string | null }
interface RecordRow {
  id: string; status: string; quantityKg: number; pickupAt: string | null;
  notes: string | null; createdAt: string; ngoId: string | null; ngoName: string | null;
  assessmentFood: string | null; assessmentId: string | null;
  deliveryAttempts: { at: string; channel: string; ok: boolean; error?: string }[];
  timeline: TimelineEv[];
}
interface Opportunity {
  id: string; status: string; quantityKg: number; pickupAt: string | null; notes: string | null; createdAt: string;
  assessment: { id: string; food: string; quantityKg: number; reason: string | null } | null;
  institution: { name: string; city: string; address: string; contactName: string; contactPhone: string; contactEmail: string } | null;
  score: number; reasons: MatchReason[];
  deliveryAttempts: { at: string; channel: string; ok: boolean; error?: string }[];
}

const MANAGE = ['SUPER_ADMIN', 'INSTITUTION_ADMIN', 'KITCHEN_MANAGER'];
const inputCls = 'mt-1 block w-full rounded-xl border border-[#E3ECE6] px-3.5 py-2 text-xs sm:text-sm bg-white text-[#0C2741] focus:ring-1 focus:ring-[#006B48]';
const btnCls = 'rounded-xl bg-[#006B48] px-4 py-2 text-xs sm:text-sm font-bold text-white shadow-sm hover:bg-[#004C35] active:scale-95 disabled:opacity-60 transition-all cursor-pointer';
const ghostCls = 'rounded-xl border border-[#E3ECE6] bg-white px-3.5 py-1.5 text-xs font-semibold text-[#0C2741] hover:bg-[#F2F7F4] active:scale-95 disabled:opacity-60 transition-all cursor-pointer';

function statusChip(s: string) {
  const cls = s === 'COMPLETED' ? 'bg-[#DCFCE7] text-[#059669]'
    : s === 'DECLINED' || s === 'CANCELLED' ? 'bg-red-100 text-red-800'
    : s === 'DRAFT' ? 'bg-stone-200 text-stone-700' : 'bg-[#FEF3C7] text-[#D97706]';
  return <span className={`rounded-full px-2.5 py-0.5 text-xs font-semibold ${cls}`}>{s}</span>;
}

export function Redistribution() {
  const { user } = useAuth();
  const isNgo = user?.role === 'NGO';
  return (
    <div className="space-y-5 animate-fadeInUpStagger">
      <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm">
        <h1 className="text-xl font-bold text-[#0C2741]">Food Distribution &amp; Redistribution</h1>
        <p className="mt-1 text-xs sm:text-sm text-gray-500">
          {isNgo
            ? 'Opportunities from institutions matched to your registered NGO. Accept, decline with a reason, or request a callback — every decision is recorded.'
            : 'Move eligible surplus from match to handover: match suitable registered NGOs, notify them truthfully, and track every state with an audit trail.'}
        </p>
      </div>
      {isNgo ? <NgoView /> : <InstitutionView canManage={!!user && MANAGE.includes(user.role)} />}
    </div>
  );
}

function useMsg() {
  const [error, setError] = useState('');
  const [msg, setMsg] = useState('');
  return { error, setError, msg, setMsg };
}

/* ---------------- Operational dashboard building blocks ---------------- */

interface OverviewNgo {
  id: string; name: string; city: string | null; address: string | null;
  contactEmail: string | null; contactPhone: string | null; isActive: boolean;
  sameCity: boolean; acceptance: 'accepting' | 'not-accepting' | 'unknown';
  matchScore: number | null; emailStatus: string; lastContact: string | null;
}
interface OverviewHistory {
  id: string; date: string; kitchen: string; createdAt: string; status: string;
  predictedKg: number | null; producedKg: number; soldKg: number; wasteKg: number;
  surplusKg: number; inconsistency: boolean; autoGenerated: boolean;
  contacted: number; sent: number; failed: number; summary: string | null; overall: string;
}
interface OverviewActivity { at: string; tone: 'ok' | 'bad' | 'idle'; text: string }
interface OverviewAutomation {
  state: 'healthy' | 'attention' | 'unknown'; schedulerArmed: boolean; nextRun: string | null;
  lastRun: { at: string; date: string } | null;
  lastSuccess: { at: string } | null;
  lastFailure: { at: string; reason: string | null } | null;
  emailService: { configured: boolean; provider?: string | null; lastEmail: { at: string; type: string } | null };
}
interface Overview {
  date: string; kitchen: { id: string; name: string }; hotel: { name: string; city: string };
  today: {
    hasRecords: boolean; records: number; producedKg: number; soldKg: number; wasteKg: number;
    surplusKg: number; inconsistency: boolean; inconsistencyMessage: string | null; predictedKg: number | null;
  };
  report: { id: string; status: string; createdAt: string; autoGenerated: boolean; summary: string | null } | null;
  distribution: {
    started: boolean; reason: string | null; assessmentId: string | null;
    matched: number; sent: number; pending: number; failed: number; accepted: number;
    acceptedKg: number; remainingKg: number; status: string;
  };
  ngos: OverviewNgo[];
  automation: OverviewAutomation;
  history: OverviewHistory[];
  activity: OverviewActivity[];
}

function emailChip(status: string) {
  const map: Record<string, { label: string; cls: string; icon: string }> = {
    sent: { label: 'Email Sent', cls: 'bg-[#DCFCE7] text-[#059669]', icon: '✓ ' },
    accepted: { label: 'Accepted', cls: 'bg-[#DCFCE7] text-[#059669]', icon: '✓ ' },
    pending: { label: 'Pending', cls: 'bg-[#FEF3C7] text-[#B45309]', icon: '◷ ' },
    failed: { label: 'Failed', cls: 'bg-red-100 text-red-800', icon: '✕ ' },
    rejected: { label: 'Rejected', cls: 'bg-red-100 text-red-800', icon: '✕ ' },
  };
  const e = map[status] ?? { label: 'Not Contacted', cls: 'bg-stone-200 text-stone-600', icon: '— ' };
  return <span className={`rounded-full px-2.5 py-0.5 text-xs font-bold ${e.cls}`}>{e.icon}{e.label}</span>;
}

function fmtTime(iso: string | null): string {
  if (!iso) return '—';
  const d = new Date(iso);
  return isNaN(d.getTime()) ? '—' : d.toLocaleString();
}

/* ---------------- Institution view ---------------- */

function InstitutionView({ canManage }: { canManage: boolean }) {
  const { user: ovUser } = useAuth();
  const kitchens = ovUser?.organization?.kitchens ?? [];
  const [assessments, setAssessments] = useState<Assessment[]>([]);
  const [assessId, setAssessId] = useState('');
  const [matches, setMatches] = useState<MatchRow[]>([]);
  const [selected, setSelected] = useState<string[]>([]);
  const [draftId, setDraftId] = useState('');
  const [records, setRecords] = useState<RecordRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [notifyResult, setNotifyResult] = useState<{ ngoId: string; channel: string; ok: boolean; error?: string }[] | null>(null);
  const { error, setError, msg, setMsg } = useMsg();
  // per-record action inputs
  const [pickupAt, setPickupAt] = useState<Record<string, string>>({});
  const [cancelReason, setCancelReason] = useState<Record<string, string>>({});

  // Operational overview (one backend snapshot per refresh)
  const [kitchenId, setKitchenId] = useState('');
  const [ov, setOv] = useState<Overview | null>(null);
  const [ovLoading, setOvLoading] = useState(true);
  const [genBusy, setGenBusy] = useState(false);
  const [genMsg, setGenMsg] = useState('');
  const [alreadyGen, setAlreadyGen] = useState(false);
  const [confirmRegen, setConfirmRegen] = useState(false);
  const [detail, setDetail] = useState<OverviewHistory | null>(null);
  const [retryBusy, setRetryBusy] = useState(false);
  const [q, setQ] = useState('');
  const [fStatus, setFStatus] = useState('all');
  const [fEmail, setFEmail] = useState('all');
  const [fAccept, setFAccept] = useState('all');
  const [sort, setSort] = useState<'match' | 'name'>('match');

  const loadOverview = useCallback(async (kid: string) => {
    if (!kid) return;
    setOvLoading(true);
    try {
      const d = await api<Overview>(`/eod/distribution-overview?kitchenUnitId=${kid}`);
      setOv(d);
      setAlreadyGen(!!d.report);
      setConfirmRegen(false);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not load distribution overview.');
    } finally {
      setOvLoading(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (!kitchenId && kitchens.length > 0) setKitchenId(kitchens[0].id);
  }, [kitchens, kitchenId]);
  useEffect(() => { if (kitchenId) void loadOverview(kitchenId); }, [kitchenId, loadOverview]);

  async function generateNow(regenerate: boolean) {
    if (!ov) return;
    setGenBusy(true);
    setGenMsg('');
    try {
      const d = await api<{ alreadyGenerated: boolean; message: string }>('/eod/generate-now', {
        method: 'POST', body: JSON.stringify({ date: ov.date, regenerate }),
      });
      setGenMsg(d.message);
      setAlreadyGen(true);
      setConfirmRegen(false);
      if (window.showToast) window.showToast(d.alreadyGenerated ? 'Report already exists' : 'Report generated successfully');
      await loadOverview(kitchenId);
    } catch (err) {
      setGenMsg(err instanceof Error ? err.message : 'Report generation failed.');
    } finally {
      setGenBusy(false);
    }
  }

  async function retryFailedEmails() {
    const aid = ov?.distribution.assessmentId;
    if (!aid) return;
    setRetryBusy(true);
    try {
      const d = await api<{ message: string }>('/redistribution/auto-retry', {
        method: 'POST', body: JSON.stringify({ assessmentId: aid }),
      });
      setMsg(d.message);
      if (window.showToast) window.showToast('Retry finished');
      await loadOverview(kitchenId);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Retry failed.');
    } finally {
      setRetryBusy(false);
    }
  }

  const visibleNgos = (ov?.ngos ?? [])
    .filter((n) => {
      if (q && !(n.name.toLowerCase().includes(q.toLowerCase()) || (n.city ?? '').toLowerCase().includes(q.toLowerCase()))) return false;
      if (fStatus === 'active' && !n.isActive) return false;
      if (fStatus === 'inactive' && n.isActive) return false;
      if (fEmail !== 'all') {
        const want = fEmail === 'not-contacted' ? 'not-contacted' : fEmail;
        if (n.emailStatus !== want) return false;
      }
      if (fAccept !== 'all' && n.acceptance !== fAccept) return false;
      return true;
    })
    .sort((a, b) => sort === 'name' ? a.name.localeCompare(b.name) : (b.matchScore ?? -1) - (a.matchScore ?? -1));

  const loadAssessments = useCallback(async () => {
    try {
      const d = await api<{ assessments: Assessment[] }>('/eligibility/assessments?verdict=ELIGIBLE');
      setAssessments(d.assessments);
    } catch { /* listed below via error */ }
  }, []);

  const loadRecords = useCallback(async () => {
    try {
      const d = await api<{ records: RecordRow[] }>('/redistribution/records');
      setRecords(d.records);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not load records.');
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const refresh = useCallback(async () => {
    setLoading(true);
    setError('');
    await Promise.all([loadAssessments(), loadRecords()]);
    setLoading(false);
  }, [loadAssessments, loadRecords]);

  useEffect(() => { void refresh(); }, [refresh]);

  async function runMatches(id: string) {
    setError('');
    setMsg('');
    setNotifyResult(null);
    try {
      const d = await api<{ matches: MatchRow[] }>(`/redistribution/matches?assessmentId=${id}`);
      setMatches(d.matches);
      setAssessId(id);
      setSelected([]);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not compute matches.');
    }
  }

  async function runNotify() {
    if (selected.length === 0) { setError('Select at least one NGO first.'); return; }
    setError('');
    setMsg('');
    setBusy(true);
    try {
      const d = await api<{ message: string; results: { ngoId: string; channel: string; ok: boolean; error?: string }[] }>(
        '/redistribution/notify',
        { method: 'POST', body: JSON.stringify({ assessmentId: assessId, ngoIds: selected, ...(draftId.trim() ? { draftId: draftId.trim() } : {}) }) });
      setMsg(d.message);
      setNotifyResult(d.results);
      setSelected([]);
      if (window.showToast) window.showToast('NGOs notified successfully!');
      await loadRecords();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Notify failed.');
    } finally {
      setBusy(false);
    }
  }

  async function transition(id: string, action: 'schedule' | 'handover' | 'cancel', body: unknown) {
    setError('');
    setMsg('');
    try {
      const d = await api<{ record: RecordRow }>(`/redistribution/${id}/${action}`, { method: 'POST', body: JSON.stringify(body) });
      setMsg(`Record ${d.record.id.slice(-6)} is now ${d.record.status}.`);
      if (window.showToast) window.showToast(`Record updated to ${d.record.status}`);
      await loadRecords();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Transition failed.');
    }
  }

  async function retry(matchId: string) {
    setError('');
    setMsg('');
    try {
      const d = await api<{ attempt: { channel: string; ok: boolean } }>(`/redistribution/notify/${matchId}/retry`, { method: 'POST' });
      setMsg(`Retried delivery (${d.attempt.channel}, ${d.attempt.ok ? 'ok' : 'failed'}). See match rows for the full attempt history.`);
      if (window.showToast) window.showToast('Retry attempt processed');
      if (assessId) await runMatches(assessId);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Retry failed.');
    }
  }

  const matchedIds = new Set(records.filter((r) => !['COMPLETED', 'CANCELLED'].includes(r.status)).map((r) => r.assessmentId));
  const unmatched = assessments.filter((a) => !matchedIds.has(a.id));

  return (
    <>
      {error && <p className="rounded-xl bg-red-50 p-3 text-xs sm:text-sm font-semibold text-red-800 border border-red-200" role="alert">{error}</p>}
      {msg && <p className="rounded-xl bg-emerald-50 p-3 text-xs sm:text-sm font-semibold text-emerald-900 border border-emerald-200" role="status">{msg}</p>}

      {/* Kitchen scope */}
      <div className="rounded-2xl border border-[#E3ECE6] bg-white px-5 py-4 shadow-sm flex flex-wrap items-center gap-3">
        <h1 className="text-xl font-bold text-[#0C2741]">Food Distribution</h1>
        <span className="text-xs text-gray-500">{ov ? `${ov.hotel.name} · ${ov.date}` : ''}</span>
        <div className="ml-auto flex items-center gap-2 text-xs sm:text-sm">
          <label htmlFor="fd-kitchen" className="font-semibold text-gray-500">Kitchen</label>
          <select id="fd-kitchen" value={kitchenId} onChange={(e) => setKitchenId(e.target.value)} className={inputCls}>
            {kitchens.map((k) => <option key={k.id} value={k.id}>{k.name}</option>)}
          </select>
          <button onClick={() => void loadOverview(kitchenId)} disabled={ovLoading} className={ghostCls}>
            {ovLoading ? 'Refreshing…' : 'Refresh'}
          </button>
        </div>
      </div>

      {ovLoading && !ov ? (
        <p className="rounded-2xl border border-[#E3ECE6] bg-white p-6 text-xs sm:text-sm text-gray-500" role="status">Loading today&apos;s distribution…</p>
      ) : ov ? (
        <>
          {/* 1 · Today's surplus */}
          <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm" data-purpose="today-surplus">
            <h2 className="text-base font-bold text-[#0C2741]">Today&apos;s Food Distribution</h2>
            {!ov.today.hasRecords ? (
              <p className="mt-2 text-xs sm:text-sm text-gray-500">No food records available for today.</p>
            ) : (
              <>
                <p className="mt-3 rounded-xl bg-emerald-50 border border-emerald-200 py-3 text-center">
                  <span className="block text-xs font-semibold text-emerald-800">Today&apos;s Surplus Food</span>
                  <span className="text-4xl font-extrabold text-[#006B48]">{ov.today.surplusKg} kg</span>
                  <span className="mt-1 block text-xs font-bold text-emerald-800">{ov.today.surplusKg > 0 ? 'SURPLUS AVAILABLE' : 'NO SURPLUS TODAY'}</span>
                </p>
                {ov.today.inconsistency && (
                  <p className="mt-2 rounded-lg bg-red-50 border border-red-200 p-2.5 text-xs font-semibold text-red-800" role="alert">
                    ⚠ {ov.today.inconsistencyMessage ?? 'Data inconsistency detected — held for review, no emails sent.'}
                  </p>
                )}
                <dl className="mt-3 grid grid-cols-2 gap-2 text-xs sm:text-sm sm:grid-cols-4">
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Food Produced (actual)</dt><dd className="font-bold text-[#0C2741]">{ov.today.producedKg} kg</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Food Sold (actual)</dt><dd className="font-bold text-[#0C2741]">{ov.today.soldKg} kg</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Food Waste (actual)</dt><dd className="font-bold text-red-700">{ov.today.wasteKg} kg</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Predicted Amount (ML)</dt><dd className="font-bold text-[#0C2741]">{ov.today.predictedKg ?? '—'}{ov.today.predictedKg != null ? ' kg' : ''}</dd></div>
                </dl>
                <p className="mt-2 text-[11px] text-gray-500">
                  Surplus calculation: Produced − Sold = Surplus → {ov.today.producedKg} − {ov.today.soldKg} = <strong className="text-[#0C2741]">{ov.today.surplusKg} kg</strong> (from today&apos;s recorded data).
                </p>
              </>
            )}
            {canManage && (
              <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-[#E3ECE6] pt-4">
                {!alreadyGen || confirmRegen ? (
                  <button onClick={() => void generateNow(confirmRegen)} disabled={genBusy || !ov.today.hasRecords} className={btnCls} title={!ov.today.hasRecords ? 'Enter today’s food records first' : 'Generate using the same backend service as the 10 PM job'}>
                    {genBusy ? 'Generating…' : confirmRegen ? 'Confirm regenerate report' : 'Generate Report Now'}
                  </button>
                ) : (
                  <>
                    <span className="text-xs sm:text-sm font-semibold text-emerald-800">✓ Today&apos;s report has already been generated{ov.report ? ` at ${fmtTime(ov.report.createdAt)}` : ''}.</span>
                    <button onClick={() => setConfirmRegen(true)} className={ghostCls}>Regenerate Report</button>
                  </>
                )}
                {confirmRegen && (
                  <button onClick={() => setConfirmRegen(false)} className={ghostCls}>Cancel</button>
                )}
              </div>
            )}
            {genMsg && <p className="mt-2 text-xs sm:text-sm font-semibold text-[#0C2741]" role="status">{genMsg}</p>}
            {ov.report && (
              <p className="mt-1 text-[11px] text-gray-500">
                Report status: {ov.report.status}{ov.report.autoGenerated ? ' · generated automatically after 10 PM' : ' · generated manually'} · {fmtTime(ov.report.createdAt)}
              </p>
            )}
          </div>

          {/* 2 · Automation status */}
          <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm" data-purpose="automation">
            <div className="flex items-center gap-2">
              <span className={`inline-block h-3 w-3 rounded-full ${ov.automation.state === 'healthy' ? 'bg-emerald-500' : ov.automation.state === 'attention' ? 'bg-amber-500' : 'bg-stone-400'}`} aria-hidden="true" />
              <h2 className="text-base font-bold text-[#0C2741]">
                System Automation · {ov.automation.state === 'healthy' ? 'Operational' : ov.automation.state === 'attention' ? 'Attention Required' : 'Not Yet Run'}
              </h2>
            </div>
            <dl className="mt-3 grid grid-cols-1 gap-2 text-xs sm:text-sm sm:grid-cols-2">
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                <dt className="text-gray-500">Daily Report Automation</dt>
                <dd className="font-bold text-[#0C2741]">{ov.automation.schedulerArmed ? '✓ Active (server scheduler)' : '— Not armed since server start'}</dd>
              </div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                <dt className="text-gray-500">Background Worker</dt>
                <dd className="font-bold text-[#0C2741]">{ov.automation.schedulerArmed ? '✓ Running' : '— Waiting for server scheduler'}</dd>
              </div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                <dt className="text-gray-500">Email Service</dt>
                <dd className="font-bold text-[#0C2741]">
                  {ov.automation.emailService.configured ? `✓ Operational${ov.automation.emailService.provider ? ` via ${ov.automation.emailService.provider.toUpperCase()}` : ''}` : '◷ Logging locally (no email server configured)'}
                </dd>
              </div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                <dt className="text-gray-500">Next Automatic Report</dt>
                <dd className="font-bold text-[#0C2741]">{ov.automation.nextRun ? `After 10:00 PM (${fmtTime(ov.automation.nextRun)})` : 'After 10:00 PM server time'}</dd>
              </div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                <dt className="text-gray-500">Last Report</dt>
                <dd className="font-bold text-[#0C2741]">{ov.automation.lastRun ? `${ov.automation.lastRun.date} — ${fmtTime(ov.automation.lastRun.at)}` : 'None yet'}</dd>
              </div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                <dt className="text-gray-500">Last Email</dt>
                <dd className="font-bold text-[#0C2741]">
                  {ov.automation.emailService.lastEmail ? fmtTime(ov.automation.emailService.lastEmail.at) : 'None yet'}
                </dd>
              </div>
            </dl>
            {ov.automation.state === 'attention' && (
              <p className="mt-2 rounded-lg bg-amber-50 border border-amber-200 p-2.5 text-xs font-semibold text-amber-900" role="alert">
                The last background run reported a problem{ov.automation.lastFailure?.reason ? `: ${ov.automation.lastFailure.reason}` : '.'} New reports still generate; failed emails can be retried below.
              </p>
            )}
          </div>

          {/* 3 · Today's distribution */}
          <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm" data-purpose="today-distribution">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h2 className="text-base font-bold text-[#0C2741]">Today&apos;s Distribution</h2>
              {canManage && ov.distribution.failed > 0 && ov.distribution.assessmentId && (
                <button onClick={() => void retryFailedEmails()} disabled={retryBusy} className={btnCls}>
                  {retryBusy ? 'Retrying…' : `Retry ${ov.distribution.failed} failed email${ov.distribution.failed === 1 ? '' : 's'}`}
                </button>
              )}
            </div>
            <dl className="mt-3 grid grid-cols-2 gap-2 text-xs sm:text-sm sm:grid-cols-4">
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Surplus</dt><dd className="font-bold text-[#0C2741]">{ov.today.surplusKg} kg</dd></div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">NGOs Matched</dt><dd className="font-bold text-[#0C2741]">{ov.distribution.matched}</dd></div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Emails Sent</dt><dd className="font-bold text-[#059669]">{ov.distribution.sent}</dd></div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Pending / Failed</dt><dd className="font-bold text-[#0C2741]">{ov.distribution.pending} / <span className={ov.distribution.failed > 0 ? 'text-red-700' : ''}>{ov.distribution.failed}</span></dd></div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Food Accepted</dt><dd className="font-bold text-[#0C2741]">{ov.distribution.acceptedKg} kg</dd></div>
              <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Food Remaining</dt><dd className="font-bold text-[#0C2741]">{ov.distribution.remainingKg} kg</dd></div>
            </dl>
            <p className="mt-2 text-xs sm:text-sm font-semibold text-[#0C2741]" role="status">Status: {ov.distribution.status}</p>
            {ov.distribution.reason && !ov.distribution.started && (
              <p className="mt-1 text-xs text-gray-500">{ov.distribution.reason}</p>
            )}
          </div>

          {/* 4 · Nearby NGOs */}
          <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm" data-purpose="ngo-directory">
            <h2 className="text-base font-bold text-[#0C2741]">Nearby Food Distribution Organizations ({visibleNgos.length})</h2>
            <p className="mt-0.5 text-xs sm:text-sm text-gray-500">
              Verified organizations from your registry, ranked for {ov.hotel.city || 'your area'}. Distances aren&apos;t
              tracked — ranking uses service area, food acceptance, pickup ability, hours and capacity.
            </p>
            <div className="mt-3 grid gap-2 text-xs sm:text-sm sm:grid-cols-5">
              <input aria-label="Search NGOs" placeholder="Search NGOs…" value={q} onChange={(e) => setQ(e.target.value)} className={inputCls} />
              <select aria-label="Filter by status" value={fStatus} onChange={(e) => setFStatus(e.target.value)} className={inputCls}>
                <option value="all">Status: All</option><option value="active">Active</option><option value="inactive">Inactive</option>
              </select>
              <select aria-label="Filter by email status" value={fEmail} onChange={(e) => setFEmail(e.target.value)} className={inputCls}>
                <option value="all">Email: All</option><option value="sent">Sent</option><option value="pending">Pending</option>
                <option value="failed">Failed</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option>
                <option value="not-contacted">Not Contacted</option>
              </select>
              <select aria-label="Filter by food acceptance" value={fAccept} onChange={(e) => setFAccept(e.target.value)} className={inputCls}>
                <option value="all">Food: All</option><option value="accepting">Accepting</option>
                <option value="not-accepting">Not Accepting</option><option value="unknown">Unknown</option>
              </select>
              <select aria-label="Sort NGOs" value={sort} onChange={(e) => setSort(e.target.value as 'match' | 'name')} className={inputCls}>
                <option value="match">Sort: Best match</option><option value="name">Sort: Name</option>
              </select>
            </div>
            {visibleNgos.length === 0 ? (
              <p className="mt-3 text-xs sm:text-sm text-gray-500">No active food-distribution organizations were found.</p>
            ) : (
              <ul className="mt-3 grid gap-3 sm:grid-cols-2">
                {visibleNgos.map((n) => (
                  <li key={n.id} className="rounded-xl border border-[#E3ECE6] p-4 text-xs sm:text-sm hover:border-[#006B48]/30 transition-all">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <p className="font-bold text-[#0C2741]">{n.name}</p>
                      <span className={`inline-flex items-center gap-1 text-xs font-bold ${n.isActive ? 'text-[#059669]' : 'text-gray-400'}`}>
                        <span className={`inline-block h-2 w-2 rounded-full ${n.isActive ? 'bg-emerald-500' : 'bg-stone-400'}`} aria-hidden="true" />
                        {n.isActive ? 'Active' : 'Inactive'}
                      </span>
                    </div>
                    <p className="mt-1 text-gray-600">
                      {n.city ?? 'Location not listed'}
                      {n.sameCity && <span className="ml-1.5 rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-bold text-emerald-900">Same area as your kitchen</span>}
                    </p>
                    <p className="mt-1 text-gray-600">Email: {n.contactEmail ?? '— no verified email —'}</p>
                    <p className="text-gray-600">Phone: {n.contactPhone ?? '—'}</p>
                    <p className="mt-1 text-gray-600">
                      Food Acceptance: <strong className="text-[#0C2741]">{
                        n.acceptance === 'accepting' ? 'Accepting Food' : n.acceptance === 'not-accepting' ? 'Not Accepting' : 'Unknown'
                      }</strong>
                      {n.matchScore !== null && <span className="ml-1 text-gray-500">(match {n.matchScore}/100)</span>}
                    </p>
                    <div className="mt-2 flex flex-wrap items-center justify-between gap-2 border-t border-[#E3ECE6] pt-2">
                      <span className="text-gray-500">Today&apos;s Email: {emailChip(n.emailStatus)}</span>
                      {n.lastContact && <span className="text-[11px] text-gray-400">Last contact: {fmtTime(n.lastContact)}</span>}
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </div>

          {/* 5 · Recent activity */}
          <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm" data-purpose="recent-activity">
            <h2 className="text-base font-bold text-[#0C2741]">Recent Activity</h2>
            {ov.activity.length === 0 ? (
              <p className="mt-2 text-xs sm:text-sm text-gray-500">No distribution activity yet.</p>
            ) : (
              <ul className="mt-3 space-y-1.5 text-xs sm:text-sm">
                {ov.activity.map((a, i) => (
                  <li key={i} className="flex items-start gap-2 rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] px-3 py-2">
                    <span className={`mt-0.5 font-bold ${a.tone === 'ok' ? 'text-[#059669]' : a.tone === 'bad' ? 'text-red-700' : 'text-gray-400'}`}>
                      {a.tone === 'ok' ? '✓' : a.tone === 'bad' ? '✕' : '•'}
                    </span>
                    <span className="text-gray-600">{fmtTime(a.at)}</span>
                    <span className="text-[#0C2741]">{a.text}</span>
                  </li>
                ))}
              </ul>
            )}
          </div>

          {/* 6 · Distribution history */}
          <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm" data-purpose="history">
            <h2 className="text-base font-bold text-[#0C2741]">Distribution History ({ov.history.length})</h2>
            {ov.history.length === 0 ? (
              <p className="mt-2 text-xs sm:text-sm text-gray-500">No reports generated yet.</p>
            ) : (
              <div className="mt-3 overflow-x-auto custom-scrollbar">
                <table className="w-full text-xs sm:text-sm min-w-[640px]">
                  <thead className="bg-[#F9FCFA] text-[#0C2741] font-semibold border-b border-[#E3ECE6]">
                    <tr className="text-left">
                      <th className="py-2.5 px-3">Date</th>
                      <th className="py-2.5 px-3">Surplus</th>
                      <th className="py-2.5 px-3">NGOs Contacted</th>
                      <th className="py-2.5 px-3">Emails Sent</th>
                      <th className="py-2.5 px-3">Status</th>
                      <th className="py-2.5 px-3">Details</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#E3ECE6]">
                    {ov.history.map((h) => (
                      <tr key={h.id} className="hover:bg-[#F9FCFA]">
                        <td className="py-2 px-3 font-medium text-[#0C2741]">{h.date}</td>
                        <td className="py-2 px-3 font-bold text-[#006B48]">{h.surplusKg} kg</td>
                        <td className="py-2 px-3 text-gray-600">{h.contacted}</td>
                        <td className="py-2 px-3 text-gray-600">{h.sent}</td>
                        <td className="py-2 px-3">
                          <span className={`rounded-full px-2 py-0.5 text-[11px] font-bold ${h.overall === 'Completed' ? 'bg-[#DCFCE7] text-[#059669]' : h.overall === 'Needs review' ? 'bg-red-100 text-red-800' : h.overall.includes('failed') ? 'bg-[#FEF3C7] text-[#B45309]' : 'bg-stone-200 text-stone-600'}`}>
                            {h.overall}
                          </span>
                        </td>
                        <td className="py-2 px-3">
                          <button onClick={() => setDetail(h)} className="text-[#006B48] font-semibold hover:underline">View</button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {detail && (
            <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/40 p-4" role="dialog" aria-modal="true" aria-label={`Report details for ${detail.date}`}>
              <div className="mt-8 w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl border border-[#E3ECE6]">
                <div className="flex items-start justify-between gap-2 border-b border-[#E3ECE6] pb-3">
                  <h2 className="text-base font-bold text-[#0C2741]">Daily Food Distribution Report · {detail.date}</h2>
                  <button onClick={() => setDetail(null)} className={ghostCls}>Close</button>
                </div>
                <dl className="mt-4 grid grid-cols-2 gap-2 text-xs sm:text-sm">
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Predicted Amount</dt><dd className="font-bold text-[#0C2741]">{detail.predictedKg ?? '—'}{detail.predictedKg != null ? ' kg' : ''}</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Actual Produced</dt><dd className="font-bold text-[#0C2741]">{detail.producedKg} kg</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Actual Sold</dt><dd className="font-bold text-[#0C2741]">{detail.soldKg} kg</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Food Waste</dt><dd className="font-bold text-red-700">{detail.wasteKg} kg</dd></div>
                  <div className="rounded-xl bg-emerald-50 border border-emerald-200 p-3 col-span-2"><dt className="text-emerald-800 font-semibold">Food Surplus</dt><dd className="text-xl font-extrabold text-[#006B48]">{detail.surplusKg} kg</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">NGOs Contacted</dt><dd className="font-bold text-[#0C2741]">{detail.contacted}</dd></div>
                  <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500">Emails Sent / Failed</dt><dd className="font-bold text-[#0C2741]">{detail.sent} / {detail.failed}</dd></div>
                </dl>
                <p className="mt-3 text-xs text-gray-500">Status: <strong className="text-[#0C2741]">{detail.overall}</strong> · {detail.kitchen}{detail.summary ? ` · ${detail.summary}` : ''}</p>
              </div>
            </div>
          )}

          {/* 7 · Advanced manual coordination (existing workflow, kept intact) */}
          <details className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm">
            <summary className="cursor-pointer text-base font-bold text-[#0C2741]">Advanced: manual NGO coordination</summary>
            <p className="mt-1 text-xs sm:text-sm text-gray-500">
              Match organizations by hand, send individual notices, and move pickups through scheduling and handover.
              The automatic overnight flow above already handles the daily routine.
            </p>
            <div className="mt-4 space-y-5">
      <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm">
        <h2 className="text-base font-bold text-[#0C2741]">Match organizations by hand</h2>        {loading ? <p className="mt-2 text-xs sm:text-sm text-gray-500" role="status">Loading confirmed surplus…</p> : assessments.length === 0 ? (
          <p className="mt-2 text-xs sm:text-sm text-stone-600">No confirmed surplus available. Confirm surplus on the <Link to="/eligibility" className="text-[#006B48] font-semibold underline">Eligibility</Link> page first.</p>
        ) : (
          <div className="mt-3 flex flex-wrap items-end gap-3 text-xs sm:text-sm">
            <div>
              <label htmlFor="rd-assess" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Assessment</label>
              <select id="rd-assess" value={assessId} onChange={(e) => void runMatches(e.target.value)} className={inputCls}>
                <option value="">— choose —</option>
                {assessments.map((a) => <option key={a.id} value={a.id}>{a.foodDescription} · {a.quantityKg} kg</option>)}
              </select>
            </div>
          </div>
        )}
        {matches.length > 0 && (
          <div className="mt-4 overflow-x-auto custom-scrollbar">
            <table className="w-full text-xs sm:text-sm min-w-[600px]">
              <thead className="bg-[#F9FCFA] text-[#0C2741] font-semibold border-b border-[#E3ECE6]">
                <tr className="text-left">
                  <th className="py-2.5 px-3">NGO</th>
                  <th className="py-2.5 px-3">Score</th>
                  <th className="py-2.5 px-3">Reasons</th>
                  <th className="py-2.5 px-3">Status</th>
                  <th className="py-2.5 px-3">Select</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E3ECE6]">
                {matches.map((m) => (
                  <tr key={m.id} className="hover:bg-[#F9FCFA] transition-colors align-top">
                    <td className="py-2.5 px-3 font-medium text-[#0C2741]">{m.ngo.name}
                      <span className="ml-1 text-xs text-gray-500">{m.ngo.isActive ? '' : '(inactive)'}</span></td>
                    <td className="py-2.5 px-3"><strong className="text-[#006B48]">{m.score}</strong> / 100</td>
                    <td className="py-2.5 px-3"><ul className="list-disc pl-4 text-stone-600 text-xs">
                      {m.reasons.map((x, i) => <li key={i}>+{x.points} {x.criterion}: {x.detail}</li>)}
                    </ul></td>
                    <td className="py-2.5 px-3">{m.status}</td>
                    <td className="py-2.5 px-3">
                      {m.eligible && m.score > 0 ? (
                        <input type="checkbox" aria-label={`Select ${m.ngo.name}`}
                          className="rounded text-[#006B48] focus:ring-[#006B48] h-4 w-4 cursor-pointer"
                          checked={selected.includes(m.ngo.id)}
                          onChange={(e) => setSelected((s) => e.target.checked ? [...s, m.ngo.id] : s.filter((x) => x !== m.ngo.id))} />
                      ) : <span className="text-xs text-gray-400">not selectable</span>}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            {canManage && (
              <div className="mt-4 flex flex-wrap items-end gap-3 text-xs sm:text-sm">
                <div>
                  <label htmlFor="rd-draft" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Link prep draft (optional id)</label>
                  <input id="rd-draft" value={draftId} onChange={(e) => setDraftId(e.target.value)} placeholder="Draft id from Food Flow" className={inputCls} />
                </div>
                <button onClick={() => void runNotify()} disabled={busy || selected.length === 0} className={btnCls}>
                  {busy ? 'Notifying…' : `Notify selected (${selected.length})`}
                </button>
              </div>
            )}
            {notifyResult && (
              <ul className="mt-3 space-y-1.5 text-xs">
                {notifyResult.map((x) => (
                  <li key={x.ngoId} className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-2.5">
                    {x.ngoId.slice(-6)}: {x.channel === 'simulated' ? 'simulated local delivery (no email was sent)' : `Attempt via ${x.channel.toUpperCase()} ${x.ok ? 'delivered' : 'failed'}`}
                    {x.error && <span className="text-red-700 font-bold"> — {x.error}</span>}
                  </li>
                ))}
              </ul>
            )}
            <button onClick={() => { const m = matches[0]; if (m) void retry(m.id); }} className="mt-3 text-xs text-[#006B48] font-semibold hover:underline">
              Retry delivery for top match
            </button>
          </div>
        )}
      </div>

      <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm">
        <h2 className="text-base font-bold text-[#0C2741]">Pickup records ({records.length})</h2>
        {records.length === 0 ? <p className="mt-2 text-xs sm:text-sm text-gray-500">No redistribution records yet.</p> : (
          <ul className="mt-3 space-y-3">
            {records.map((r) => (
              <li key={r.id} className="rounded-xl border border-[#E3ECE6] p-4 text-xs sm:text-sm hover:border-[#006B48]/30 transition-all">
                <div className="flex flex-wrap items-center gap-2">
                  <p className="font-bold text-[#0C2741]">{r.assessmentFood ?? 'Surplus'} · {r.quantityKg} kg → {r.ngoName ?? '—'}</p>
                  {statusChip(r.status)}
                </div>
                {r.notes && <p className="mt-1 text-gray-600">{r.notes}</p>}
                {r.pickupAt && <p className="text-gray-600">Pickup: {new Date(r.pickupAt).toLocaleString()}</p>}
                {r.deliveryAttempts.length > 0 && (
                  <p className="mt-1 text-xs text-gray-500">Delivery: {r.deliveryAttempts.map((a) => `${a.channel} ${a.ok ? 'ok' : 'failed'}@${new Date(a.at).toLocaleTimeString()}`).join(' · ')}</p>
                )}
                <details className="mt-2 text-xs"><summary className="cursor-pointer text-[#006B48] font-semibold hover:underline">Audit timeline ({r.timeline.length})</summary>
                  <ul className="mt-1 list-disc pl-5 text-gray-600">
                    {r.timeline.map((t, i) => <li key={i}>{new Date(t.at).toLocaleString()} — {t.action}</li>)}
                  </ul>
                </details>
                {canManage && (
                  <div className="mt-3 flex flex-wrap items-end gap-2 pt-2 border-t border-[#E3ECE6]">
                    {r.status === 'ACCEPTED' && (
                      <span className="flex items-end gap-1.5">
                        <input type="datetime-local" aria-label="Pickup time" id={`pk-${r.id}`}
                          defaultValue={r.pickupAt ? new Date(r.pickupAt).toISOString().slice(0, 16) : ''}
                          onChange={(e) => setPickupAt((s) => ({ ...s, [r.id]: e.target.value }))} className="rounded-xl border border-[#E3ECE6] px-2.5 py-1.5 text-xs text-[#0C2741]" />
                        <button onClick={() => void transition(r.id, 'schedule', { pickupAt: pickupAt[r.id] ? new Date(pickupAt[r.id]).toISOString() : new Date().toISOString() })} className={ghostCls}>Confirm schedule</button>
                      </span>
                    )}
                    {r.status === 'PICKUP_SCHEDULED' && <button onClick={() => void transition(r.id, 'handover', {})} className={ghostCls}>Confirm handover</button>}
                    {!['COMPLETED', 'CANCELLED'].includes(r.status) && (
                      <span className="flex items-end gap-1.5">
                        <input aria-label="Cancel reason" placeholder="Cancel reason (min 5)" value={cancelReason[r.id] ?? ''}
                          onChange={(e) => setCancelReason((s) => ({ ...s, [r.id]: e.target.value }))} className="rounded-xl border border-[#E3ECE6] px-2.5 py-1.5 text-xs text-[#0C2741]" />
                        <button onClick={() => void transition(r.id, 'cancel', { reason: cancelReason[r.id] ?? '' })} className={ghostCls}>Cancel</button>
                      </span>
                    )}
                  </div>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>

      <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm">
        <h2 className="text-base font-bold text-[#0C2741]">Waiting list: confirmed surplus not yet moving ({unmatched.length})</h2>
        {unmatched.length === 0 ? <p className="mt-2 text-xs sm:text-sm text-gray-500">Nothing waiting — every confirmed surplus has an active pickup, or none exists.</p> : (
          <ul className="mt-3 space-y-1.5 text-xs sm:text-sm">
            {unmatched.map((a) => (
              <li key={a.id} className="rounded-xl bg-[#FFFDF7] border border-[#FDE8B5] p-3 text-[#B45309]">
                {a.foodDescription} · {a.quantityKg} kg — no active redistribution. Match above, or record disposal on the <Link to="/eligibility" className="text-[#006B48] font-bold underline">Eligibility</Link> page. Nothing disappears silently.
              </li>
            ))}
          </ul>
        )}
      </div>
            </div>
          </details>
      </> ) : null}
    </>
  );
}

/* ---------------- NGO view ---------------- */

function NgoView() {
  const [records, setRecords] = useState<Opportunity[]>([]);
  const [history, setHistory] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [msg, setMsg] = useState('');
  const [busyId, setBusyId] = useState<string | null>(null);
  const [forms, setForms] = useState<Record<string, { pickupAt: string; reason: string; message: string; phone: string }>>({});

  const load = useCallback(async (hist: boolean) => {
    setLoading(true);
    setError('');
    try {
      const d = await api<{ records: Opportunity[] }>(`/redistribution/opportunities${hist ? '?history=true' : ''}`);
      setRecords(d.records);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not load opportunities.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { void load(history); }, [load, history]);

  const f = (id: string) => forms[id] ?? { pickupAt: '', reason: '', message: '', phone: '' };
  const setF = (id: string, patch: Partial<{ pickupAt: string; reason: string; message: string; phone: string }>) =>
    setForms((s) => ({ ...s, [id]: { ...f(id), ...patch } }));

  async function act(id: string, action: 'accept' | 'decline' | 'callback' | 'confirm-receipt', body: unknown) {
    setError('');
    setMsg('');
    setBusyId(id);
    try {
      const d = await api<{ record?: { status: string }; message: string }>(`/redistribution/${id}/${action}`, { method: 'POST', body: JSON.stringify(body) });
      setMsg(d.message ?? `Done (now ${d.record?.status ?? 'updated'}).`);
      if (window.showToast) window.showToast('Opportunity updated successfully');
      await load(history);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Action failed.');
    } finally {
      setBusyId(null);
    }
  }

  return (
    <>
      {error && <p className="rounded-xl bg-red-50 p-3 text-xs sm:text-sm font-semibold text-red-800 border border-red-200" role="alert">{error}</p>}
      {msg && <p className="rounded-xl bg-emerald-50 p-3 text-xs sm:text-sm font-semibold text-emerald-900 border border-emerald-200" role="status">{msg}</p>}
      <div className="rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <h2 className="text-base font-bold text-[#0C2741]">Opportunities for your NGO ({records.length})</h2>
          <button onClick={() => setHistory((h) => !h)} className={ghostCls} aria-pressed={history}>
            {history ? 'Hide history' : 'Show history'}
          </button>
        </div>
        {loading ? <p className="mt-2 text-xs sm:text-sm text-gray-500" role="status">Loading…</p> : records.length === 0 ? (
          <p className="mt-2 text-xs sm:text-sm text-stone-600">No open opportunities right now. New matches arrive here with an inbox notification.</p>
        ) : (
          <ul className="mt-4 space-y-3">
            {records.map((o) => (
              <li key={o.id} className="rounded-xl border border-[#E3ECE6] p-4 text-xs sm:text-sm hover:border-[#006B48]/30 transition-all">
                <div className="flex flex-wrap items-center gap-2">
                  <p className="font-bold text-[#0C2741]">{o.assessment?.food ?? 'Surplus'} · {o.quantityKg} kg</p>
                  {statusChip(o.status)}
                  <span className="text-xs text-gray-500 font-medium">match score {o.score}/100</span>
                </div>
                <p className="mt-1 text-gray-600">{o.institution?.name} ({o.institution?.city}) — {o.institution?.address}</p>
                <p className="text-gray-600">Contact: {o.institution?.contactName}, {o.institution?.contactPhone}, {o.institution?.contactEmail}</p>
                {o.assessment?.reason && <p className="mt-1 text-gray-600">Eligibility notes: {o.assessment.reason}</p>}
                {o.pickupAt && <p className="text-gray-600">Pickup: {new Date(o.pickupAt).toLocaleString()}</p>}
                {o.reasons.length > 0 && (
                  <details className="mt-2 text-xs"><summary className="cursor-pointer text-[#006B48] font-semibold hover:underline">Why matched to us</summary>
                    <ul className="mt-1 list-disc pl-5 text-gray-600">
                      {o.reasons.map((x, i) => <li key={i}>+{x.points} {x.criterion}: {x.detail}</li>)}
                    </ul>
                  </details>
                )}
                {o.deliveryAttempts.length > 0 && (
                  <p className="mt-1 text-xs text-gray-500">Delivery: {o.deliveryAttempts.map((a) => `${a.channel} ${a.ok ? 'ok' : 'failed'}`).join(' · ')}</p>
                )}
                {o.status === 'NOTIFIED' && (
                  <div className="mt-3 grid gap-3 sm:grid-cols-2 pt-2 border-t border-[#E3ECE6]">
                    <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                      <label htmlFor={`pa-${o.id}`} className="block text-xs font-semibold text-[#0C2741]">Intended pickup (accept)</label>
                      <input id={`pa-${o.id}`} type="datetime-local" value={f(o.id).pickupAt} onChange={(e) => setF(o.id, { pickupAt: e.target.value })} className={inputCls} />
                      <button disabled={busyId === o.id} onClick={() => void act(o.id, 'accept', { intendedPickupAt: f(o.id).pickupAt ? new Date(f(o.id).pickupAt).toISOString() : '' })} className={`${btnCls} mt-2`}>Accept</button>
                    </div>
                    <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3">
                      <label htmlFor={`dr-${o.id}`} className="block text-xs font-semibold text-[#0C2741]">Decline reason (min 5 chars)</label>
                      <input id={`dr-${o.id}`} value={f(o.id).reason} onChange={(e) => setF(o.id, { reason: e.target.value })} className={inputCls} />
                      <div className="mt-2 flex gap-2">
                        <button disabled={busyId === o.id} onClick={() => void act(o.id, 'decline', { reason: f(o.id).reason })} className={ghostCls}>Decline</button>
                      </div>
                      <label htmlFor={`cb-${o.id}`} className="mt-3 block text-xs font-semibold text-[#0C2741]">Callback message / phone (optional)</label>
                      <input id={`cb-${o.id}`} value={f(o.id).message} onChange={(e) => setF(o.id, { message: e.target.value })} placeholder="Message" className={inputCls} />
                      <input aria-label="Callback phone" value={f(o.id).phone} onChange={(e) => setF(o.id, { phone: e.target.value })} placeholder="Phone" className={`${inputCls} mt-1.5`} />
                      <button disabled={busyId === o.id} onClick={() => void act(o.id, 'callback', { message: f(o.id).message || undefined, phone: f(o.id).phone || undefined })} className={`${ghostCls} mt-2`}>Request callback</button>
                    </div>
                  </div>
                )}
                {o.status === 'HANDED_OVER' && (
                  <button disabled={busyId === o.id} onClick={() => void act(o.id, 'confirm-receipt', {})} className={`${btnCls} mt-3`}>
                    Confirm receipt (complete)
                  </button>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>
    </>
  );
}
