import { useCallback, useEffect, useState } from 'react';
import { API_BASE, api, getToken } from '../api';
import { useAuth } from '../auth-context';

interface ReportData {
  type: string; from: string; to: string;
  filters: Record<string, string>;
  generatedAt: string;
  production: { targetTotal: number; actualTotal: number; daily: { date: string; target: number; actual: number }[]; byFood: { foodItemId: string; food: string; target: number; actual: number }[] };
  sales: { soldKg: number; remainingKg: number; producedKg: number; utilizationPct: number | null };
  waste: { totalKg: number; pctOfProduced: number | null };
  surplus: { predictedKg: number; actualRemainingKg: number; eligibleKg: number; redistributedKg: number; unredistributedKg: number; redistributionRatePct: number | null };
  ai: { meanAbsPctErr: number | null; accuracyDefinition: string };
  sustainability: { foodSavedKg: number; wasteReducedKg: number; costSavedEstimate: number; co2AvoidedKgEstimate: number; howCalculated: string[] };
}

interface Factor {
  id: string; key: string; name: string; value: number; unit: string;
  description: string | null; source: string | null; effectiveDate: string | null;
  isActive: boolean; organizationId: string | null; category: string | null; foodItemId: string | null;
}

interface Snapshot {
  id: string; date: string; foodSavedKg: number; wasteReducedKg: number;
  co2AvoidedKgEstimate: number; costSavedEstimate: number; createdAt: string;
  detail: { filters?: unknown; method?: string; howCalculated?: string[] } | null;
}

const MANAGE = ['SUPER_ADMIN', 'INSTITUTION_ADMIN', 'KITCHEN_MANAGER'];
const input = 'mt-1 w-full rounded-xl border border-[#E3ECE6] px-3.5 py-2 text-xs sm:text-sm bg-white text-[#0C2741] focus:ring-1 focus:ring-[#006B48]';
const card = 'rounded-2xl border border-[#E3ECE6] bg-white p-5 md:p-6 shadow-sm';
const todayIso = () => new Date().toISOString().slice(0, 10);

async function authedGet(path: string): Promise<Response> {
  const headers: Record<string, string> = {};
  const token = getToken();
  if (token) headers['Authorization'] = `Bearer ${token}`;
  return fetch(`${API_BASE}${path}`, { headers });
}

export function Reports() {
  const { user } = useAuth();
  const kitchens = user?.organization?.kitchens ?? [];
  const canManage = !!user && MANAGE.includes(user.role);
  const [type, setType] = useState('daily');
  const [date, setDate] = useState(todayIso);
  const [kitchen, setKitchen] = useState('');
  const [meal, setMeal] = useState('');
  const [food, setFood] = useState('');
  const [foods, setFoods] = useState<{ id: string; name: string }[]>([]);
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(false);
  const [dlBusy, setDlBusy] = useState('');
  const [error, setError] = useState('');
  const [msg, setMsg] = useState('');

  const [factors, setFactors] = useState<Factor[]>([]);
  const [fKey, setFKey] = useState('');
  const [fName, setFName] = useState('');
  const [fValue, setFValue] = useState('');
  const [fUnit, setFUnit] = useState('');
  const [fSource, setFSource] = useState('');
  const [fDate, setFDate] = useState(todayIso);
  const [fCategory, setFCategory] = useState('');
  const [fFood, setFFood] = useState('');
  const [fError, setFError] = useState('');
  const [fBusy, setFBusy] = useState(false);

  const [snapshots, setSnapshots] = useState<Snapshot[]>([]);
  const [sBusy, setSBusy] = useState(false);

  // Phase 3: automatic daily food-waste reports (after 10 PM + manual retry)
  interface AutoAccuracy {
    predictedKg?: number | null; producedKg?: number; soldKg?: number; surplusKg?: number; autoGenerated?: boolean;
    inconsistency?: boolean; inconsistencyMessage?: string | null;
    predictionError?: { absErrKg: number | null; pctErr: number | null; bias: string | null } | null;
    mlValidation?: { foods: number; avgRmse: number } | null;
    summary?: { text: string; source: string } | null;
    meanAbsPctErr?: number | null;
  }
  interface EodReport {
    id: string; date: string; kitchen: string;
    totalPreparedKg: number; totalServedKg: number; totalWasteKg: number; totalSurplusKg: number;
    notes: string | null; status: string; accuracy: AutoAccuracy | null; qualityNotes: string | null;
  }
  const [eodReports, setEodReports] = useState<EodReport[]>([]);
  const [eodLoading, setEodLoading] = useState(false);
  const [autoBusy, setAutoBusy] = useState(false);
  const [autoMsg, setAutoMsg] = useState('');

  const loadEodReports = useCallback(async () => {
    setEodLoading(true);
    try {
      const d = await api<{ reports: EodReport[] }>('/eod/reports');
      setEodReports(d.reports);
    } catch { /* section stays empty on failure */ } finally {
      setEodLoading(false);
    }
  }, []);

  async function runAutoNow() {
    setAutoMsg('');
    setAutoBusy(true);
    try {
      const d = await api<{ message: string }>('/eod/auto-run', { method: 'POST', body: JSON.stringify({}) });
      setAutoMsg(d.message);
      if (window.showToast) window.showToast('Auto-report sweep finished');
      await loadEodReports();
    } catch (err) {
      setAutoMsg(err instanceof Error ? err.message : 'Auto-report sweep failed.');
    } finally {
      setAutoBusy(false);
    }
  }

  const loadFoods = useCallback(async () => {
    try {
      const d = await api<{ items: { id: string; name: string }[] }>('/food-items');
      setFoods(d.items);
    } catch { /* convenience only */ }
  }, []);

  const loadFactors = useCallback(async () => {
    try {
      const d = await api<{ factors: Factor[] }>('/impact/factors');
      setFactors(d.factors);
    } catch { /* shown via error on action */ }
  }, []);

  const loadSnapshots = useCallback(async () => {
    try {
      const d = await api<{ snapshots: Snapshot[] }>('/impact/snapshots');
      setSnapshots(d.snapshots);
    } catch { /* supplementary */ }
  }, []);

  useEffect(() => { void loadFoods(); void loadFactors(); void loadSnapshots(); void loadEodReports(); }, [loadFoods, loadFactors, loadSnapshots, loadEodReports]);

  function params(): string {
    const p = new URLSearchParams({ type, date });
    if (kitchen) p.set('kitchenUnitId', kitchen);
    if (meal) p.set('mealType', meal);
    if (food) p.set('foodItemId', food);
    return p.toString();
  }

  async function loadReport() {
    setError('');
    setMsg('');
    setLoading(true);
    try {
      const d = await api<{ report: ReportData }>(`/reports/data?${params()}`);
      setReport(d.report);
      if (window.showToast) window.showToast('Report generated successfully');
    } catch (err) {
      setReport(null);
      setError(err instanceof Error ? err.message : 'Could not build report.');
    } finally {
      setLoading(false);
    }
  }

  async function download(ext: 'csv' | 'xlsx' | 'pdf') {
    setError('');
    setMsg('');
    setDlBusy(ext);
    try {
      const res = await authedGet(`/reports/export.${ext}?${params()}`);
      if (!res.ok) {
        const j = await res.json().catch(() => ({}));
        throw new Error((j as { error?: string }).error ?? `Export failed (${res.status}).`);
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const r = report;
      a.download = r ? `report-${r.type}-${r.from}-to-${r.to}.${ext}` : `report.${ext}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
      setMsg(`${ext.toUpperCase()} downloaded with the currently displayed data. The export was audited.`);
      if (window.showToast) window.showToast(`${ext.toUpperCase()} exported successfully!`);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Download failed.');
    } finally {
      setDlBusy('');
    }
  }

  async function saveFactor(e: React.FormEvent) {
    e.preventDefault();
    setFError('');
    setMsg('');
    setFBusy(true);
    try {
      const d = await api<{ message: string }>('/impact/factors', { method: 'POST',
        body: JSON.stringify({ key: fKey.trim().toUpperCase(), name: fName.trim(), value: Number(fValue),
          unit: fUnit.trim(), source: fSource.trim(), effectiveDate: fDate,
          category: fCategory.trim() || undefined, foodItemId: fFood || undefined }) });
      setMsg(d.message);
      setFKey(''); setFName(''); setFValue(''); setFUnit(''); setFSource(''); setFCategory(''); setFFood('');
      if (window.showToast) window.showToast('Impact factor saved');
      await loadFactors();
    } catch (err) {
      setFError(err instanceof Error ? err.message : 'Save failed.');
    } finally {
      setFBusy(false);
    }
  }

  async function saveSnapshot() {
    setError('');
    setMsg('');
    if (!report) {
      setError('Build a report first — snapshots persist the displayed numbers.');
      return;
    }
    setSBusy(true);
    try {
      const d = await api<{ message: string }>('/impact/snapshots', { method: 'POST',
        body: JSON.stringify({ from: report.from, to: report.to,
          ...(kitchen ? { kitchenUnitId: kitchen } : {}),
          ...(meal ? { mealType: meal } : {}), ...(food ? { foodItemId: food } : {}) }) });
      setMsg(d.message);
      if (window.showToast) window.showToast('Impact snapshot persisted');
      await loadSnapshots();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Snapshot failed.');
    } finally {
      setSBusy(false);
    }
  }

  return (
    <div className="space-y-5 animate-fadeInUpStagger">
      <div className={card}>
        <h1 className="text-xl font-bold text-[#0C2741]">Operational &amp; ESG Reports</h1>
        <p className="mt-1 text-xs sm:text-sm text-gray-500">
          Daily, weekly, monthly, and ESG/sustainability reports from live data. Exports contain exactly what is displayed — audited and verified.
        </p>
        <div className="mt-4 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">
          <div>
            <label htmlFor="rp-type" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Type</label>
            <select id="rp-type" value={type} onChange={(e) => setType(e.target.value)} className={input}>
              <option value="daily">Daily</option><option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option><option value="esg">ESG / sustainability</option>
            </select>
          </div>
          <div>
            <label htmlFor="rp-date" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Anchor date</label>
            <input id="rp-date" type="date" value={date} onChange={(e) => setDate(e.target.value)} className={input} />
          </div>
          <div>
            <label htmlFor="rp-kitchen" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Kitchen</label>
            <select id="rp-kitchen" value={kitchen} onChange={(e) => setKitchen(e.target.value)} className={input}>
              <option value="">All kitchens</option>{kitchens.map((k) => <option key={k.id} value={k.id}>{k.name}</option>)}
            </select>
          </div>
          <div>
            <label htmlFor="rp-meal" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Meal</label>
            <select id="rp-meal" value={meal} onChange={(e) => setMeal(e.target.value)} className={input}>
              <option value="">All meals</option><option value="BREAKFAST">Breakfast</option><option value="LUNCH">Lunch</option><option value="DINNER">Dinner</option>
            </select>
          </div>
          <div>
            <label htmlFor="rp-food" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Food</label>
            <select id="rp-food" value={food} onChange={(e) => setFood(e.target.value)} className={input}>
              <option value="">All items</option>{foods.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}
            </select>
          </div>
          <div className="flex items-end">
            <button onClick={() => void loadReport()} disabled={loading} className="w-full rounded-xl bg-[#006B48] px-4 py-2 text-xs sm:text-sm font-bold text-white shadow-sm hover:bg-[#004C35] active:scale-95 disabled:opacity-60 transition-all cursor-pointer">
              {loading ? 'Building…' : 'Build Report'}
            </button>
          </div>
        </div>
        {error && <p className="mt-3 rounded-xl bg-red-50 p-3 text-xs sm:text-sm font-semibold text-red-800 border border-red-200" role="alert">{error}</p>}
        {msg && <p className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs sm:text-sm font-semibold text-emerald-900 border border-emerald-200" role="status">{msg}</p>}
      </div>

      {report && (
        <div className={card}>
          <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#E3ECE6] pb-3">
            <h2 className="text-base font-bold text-[#0C2741]">{report.type.toUpperCase()} report · {report.from} to {report.to}</h2>
            <div className="flex gap-2 text-xs">
              {(['csv', 'xlsx', 'pdf'] as const).map((ext) => (
                <button key={ext} onClick={() => void download(ext)} disabled={dlBusy !== ''}
                  className="rounded-xl border border-[#E3ECE6] bg-white px-3.5 py-1.5 font-bold text-[#0C2741] hover:bg-[#F2F7F4] active:scale-95 disabled:opacity-60 transition-all cursor-pointer">
                  {dlBusy === ext ? 'Exporting…' : `Download ${ext.toUpperCase()}`}
                </button>
              ))}
            </div>
          </div>
          <dl className="mt-4 grid grid-cols-2 gap-3 text-xs sm:text-sm sm:grid-cols-4">
            <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500 font-medium">Target / actual</dt><dd className="font-bold text-[#0C2741] mt-1">{report.production.targetTotal} / {report.production.actualTotal} kg</dd></div>
            <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500 font-medium">Sold (util.)</dt><dd className="font-bold text-[#0C2741] mt-1">{report.sales.soldKg} kg ({report.sales.utilizationPct ?? 'n/a'}%)</dd></div>
            <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500 font-medium">Waste</dt><dd className="font-bold text-red-700 mt-1">{report.waste.totalKg} kg</dd></div>
            <div className="rounded-xl bg-[#ECFDF5] border border-emerald-200 p-3" title="Operational estimate: food saved from disposal via prevention and redistribution"><dt className="text-emerald-800 font-medium">Food saved</dt><dd className="font-bold text-[#006B48] mt-1">{report.sustainability.foodSavedKg} kg</dd></div>
            <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3" title="Configured cost savings estimate (INR per kg food rescued)"><dt className="text-gray-500 font-medium">Cost saved (est.)</dt><dd className="font-bold text-[#0C2741] mt-1">₹ {report.sustainability.costSavedEstimate.toLocaleString()}</dd></div>
            <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3" title="Configured emissions estimate (kg CO2e avoided per kg food rescued)"><dt className="text-gray-500 font-medium">CO2e avoided (est.)</dt><dd className="font-bold text-[#006B48] mt-1">{report.sustainability.co2AvoidedKgEstimate} kgCO2e</dd></div>
            <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500 font-medium">Redistributed</dt><dd className="font-bold text-[#D97706] mt-1">{report.surplus.redistributedKg} kg</dd></div>
            <div className="rounded-xl bg-[#F9FCFA] border border-[#E3ECE6] p-3"><dt className="text-gray-500 font-medium">Forecast error</dt><dd className="font-bold text-[#0C2741] mt-1">{report.ai.meanAbsPctErr ?? 'n/a'}{report.ai.meanAbsPctErr !== null ? '%' : ''}</dd></div>
          </dl>
          <details className="mt-3 text-xs"><summary className="cursor-pointer font-bold text-[#006B48] hover:underline">Methodology &amp; how calculated</summary>
            <ul className="mt-2 list-disc pl-5 text-gray-600 space-y-1">
              {report.sustainability.howCalculated.map((h, i) => <li key={i}>{h}</li>)}
              <li>{report.ai.accuracyDefinition}</li>
              <li>Cost and CO2e figures are estimates derived from configured factors, not measurements. No guaranteed reductions are claimed.</li>
            </ul>
          </details>
          {canManage && <button onClick={() => void saveSnapshot()} disabled={sBusy} className="mt-4 rounded-xl bg-[#006B48] px-4 py-2 text-xs font-bold text-white shadow hover:bg-[#004C35] active:scale-95 disabled:opacity-60 transition-all cursor-pointer">{sBusy ? 'Saving…' : 'Persist as Impact Snapshot'}</button>}
        </div>
      )}

      <div className={card}>
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div>
            <h2 className="text-base font-bold text-[#0C2741]">Automatic Daily Food Waste Reports</h2>
            <p className="mt-1 text-xs sm:text-sm text-gray-500">
              Generated automatically after 10 PM from database actuals + ML predictions. Surplus is computed
              deterministically (produced − sold) — never by AI. Figures below are stored reports, not live estimates.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button onClick={() => void loadEodReports()} disabled={eodLoading}
              className="rounded-xl border border-[#E3ECE6] bg-white px-3.5 py-1.5 text-xs font-bold text-[#0C2741] hover:bg-[#F2F7F4] disabled:opacity-60 cursor-pointer">
              {eodLoading ? 'Refreshing…' : 'Refresh'}
            </button>
            {canManage && (
              <button onClick={() => void runAutoNow()} disabled={autoBusy} title="Retry the after-10PM sweep now (e.g. after a failed night run)"
                className="rounded-xl bg-[#006B48] px-3.5 py-1.5 text-xs font-bold text-white shadow hover:bg-[#004C35] disabled:opacity-60 cursor-pointer">
                {autoBusy ? 'Running…' : 'Run auto-reports now'}
              </button>
            )}
          </div>
        </div>
        {autoMsg && <p className="mt-3 rounded-xl bg-emerald-50 p-3 text-xs font-semibold text-emerald-900 border border-emerald-200" role="status">{autoMsg}</p>}
        {eodReports.length === 0 ? (
          <p className="mt-3 text-xs sm:text-sm text-gray-500">
            {eodLoading ? 'Loading…' : 'No day-close reports yet. Close a day from End of Day, or run the auto-report sweep.'}
          </p>
        ) : (
          <div className="mt-4 space-y-3">
            {eodReports.slice(0, 10).map((r) => (
              <div key={r.id} className="rounded-xl border border-[#E3ECE6] bg-[#F9FCFA] p-4">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <p className="text-sm font-bold text-[#0C2741]">
                    Daily Food Waste Report · {r.date.slice(0, 10)} · {r.kitchen}
                  </p>
                  <div className="flex gap-1.5 text-[10px] font-bold">
                    {r.accuracy?.autoGenerated && (
                      <span className="rounded-full bg-indigo-100 px-2 py-0.5 text-indigo-800 border border-indigo-200">AUTO after 10 PM</span>
                    )}
                    <span className="rounded-full bg-stone-200 px-2 py-0.5 text-stone-700">{r.status}</span>
                  </div>
                </div>
                <p className="mt-2 text-center rounded-lg bg-emerald-50 border border-emerald-200 py-2">
                  <span className="text-xs font-semibold text-emerald-800">Today&apos;s Surplus Food: </span>
                  <span className="text-2xl font-extrabold text-[#006B48]">{r.totalSurplusKg} kg</span>
                </p>
                {r.accuracy?.inconsistency && (
                  <p className="mt-2 rounded-lg bg-red-50 border border-red-200 p-2 text-xs font-semibold text-red-800" role="alert">
                    ⚠ {r.accuracy.inconsistencyMessage ?? 'Data inconsistency detected: sold exceeds produced. Held for review.'}
                  </p>
                )}
                <dl className="mt-2 grid grid-cols-2 gap-2 text-xs sm:grid-cols-5">
                  <div className="rounded-lg bg-white border border-[#E3ECE6] p-2"><dt className="text-gray-500">Predicted (ML)</dt><dd className="font-bold text-[#0C2741]">{r.accuracy?.predictedKg ?? 'n/a'}{r.accuracy?.predictedKg != null ? ' kg' : ''}</dd></div>
                  <div className="rounded-lg bg-white border border-[#E3ECE6] p-2"><dt className="text-gray-500">Actual produced</dt><dd className="font-bold text-[#0C2741]">{r.accuracy?.producedKg ?? r.totalPreparedKg} kg</dd></div>
                  <div className="rounded-lg bg-white border border-[#E3ECE6] p-2"><dt className="text-gray-500">Actual sold</dt><dd className="font-bold text-[#0C2741]">{r.accuracy?.soldKg ?? r.totalServedKg} kg</dd></div>
                  <div className="rounded-lg bg-white border border-[#E3ECE6] p-2"><dt className="text-gray-500">Waste</dt><dd className="font-bold text-red-700">{r.totalWasteKg} kg</dd></div>
                  <div className="rounded-lg bg-white border border-[#E3ECE6] p-2"><dt className="text-gray-500">Prediction error</dt><dd className="font-bold text-[#0C2741]">{r.accuracy?.predictionError?.absErrKg ?? r.accuracy?.meanAbsPctErr ?? 'n/a'}{r.accuracy?.predictionError?.absErrKg != null ? ' kg' : ''}</dd></div>
                </dl>
                {r.accuracy?.mlValidation && (
                  <p className="mt-1.5 text-[11px] text-gray-500">
                    Model performance: {r.accuracy.mlValidation.foods} ML-validated food(s), avg RMSE {r.accuracy.mlValidation.avgRmse} kg.
                  </p>
                )}
                {r.accuracy?.summary?.text && (
                  <p className="mt-1.5 text-[11px] text-gray-600 italic">{r.accuracy.summary.text}</p>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      <div className={card}>
        <h2 className="text-base font-bold text-[#0C2741]">Impact Factors</h2>
        <p className="mt-1 text-xs sm:text-sm text-gray-500">Every factor needs a name, value, unit, source, effective date, and active status. Resolution: food item → category → organization → global. No unexplained hardcoded numbers.</p>
        {factors.length === 0 ? <p className="mt-2 text-xs sm:text-sm text-gray-500">None configured.</p> : (
          <div className="mt-3 overflow-x-auto custom-scrollbar">
            <table className="w-full text-xs sm:text-sm min-w-[600px]">
              <thead className="bg-[#F9FCFA] text-[#0C2741] font-semibold border-b border-[#E3ECE6]">
                <tr className="text-left">
                  <th className="py-2.5 px-3">Key</th>
                  <th className="py-2.5 px-3">Name</th>
                  <th className="py-2.5 px-3">Value</th>
                  <th className="py-2.5 px-3">Scope</th>
                  <th className="py-2.5 px-3">Source</th>
                  <th className="py-2.5 px-3">Active</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E3ECE6]">
                {factors.map((f) => (
                  <tr key={f.id} className="hover:bg-[#F9FCFA] transition-colors">
                    <td className="py-2 px-3 font-mono text-xs text-[#006B48] font-bold">{f.key}</td>
                    <td className="py-2 px-3 font-medium text-[#0C2741]">{f.name}</td>
                    <td className="py-2 px-3 font-semibold text-[#0C2741]">{f.value} {f.unit}</td>
                    <td className="py-2 px-3 text-gray-600">{f.foodItemId ? `food:${f.foodItemId.slice(-6)}` : f.category ? `cat:${f.category}` : f.organizationId ? 'org' : 'global'}</td>
                    <td className="py-2 px-3 text-gray-600">{f.source ?? '—'}</td>
                    <td className="py-2 px-3">{f.isActive ? <span className="text-[#059669] font-bold">yes</span> : <span className="text-gray-400">no</span>}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
        {canManage ? (
          <form onSubmit={saveFactor} className="mt-4 grid gap-3 text-xs sm:text-sm sm:grid-cols-3 pt-3 border-t border-[#E3ECE6]">
            <div><label htmlFor="fx-key" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Key</label><input id="fx-key" value={fKey} onChange={(e) => setFKey(e.target.value)} required className={input} placeholder="COST_PER_KG_FOOD" /></div>
            <div><label htmlFor="fx-name" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Name</label><input id="fx-name" value={fName} onChange={(e) => setFName(e.target.value)} required className={input} /></div>
            <div><label htmlFor="fx-value" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Value</label><input id="fx-value" type="number" min={0} step="any" value={fValue} onChange={(e) => setFValue(e.target.value)} required className={input} /></div>
            <div><label htmlFor="fx-unit" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Unit</label><input id="fx-unit" value={fUnit} onChange={(e) => setFUnit(e.target.value)} required className={input} placeholder="INR/kg" /></div>
            <div><label htmlFor="fx-source" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Source (required)</label><input id="fx-source" value={fSource} onChange={(e) => setFSource(e.target.value)} required className={input} /></div>
            <div><label htmlFor="fx-date" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Effective date</label><input id="fx-date" type="date" value={fDate} onChange={(e) => setFDate(e.target.value)} required className={input} /></div>
            <div><label htmlFor="fx-cat" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Category scope (optional)</label><input id="fx-cat" value={fCategory} onChange={(e) => setFCategory(e.target.value)} className={input} /></div>
            <div><label htmlFor="fx-food" className="block text-[11px] font-bold text-gray-500 uppercase tracking-wider">Food item scope</label>
              <select id="fx-food" value={fFood} onChange={(e) => setFFood(e.target.value)} className={input}>
                <option value="">None (broader scope)</option>{foods.map((f) => <option key={f.id} value={f.id}>{f.name}</option>)}
              </select></div>
            <div className="flex items-end"><button type="submit" disabled={fBusy} className="w-full rounded-xl bg-[#006B48] px-4 py-2 font-bold text-white shadow hover:bg-[#004C35] active:scale-95 disabled:opacity-60 transition-all cursor-pointer">{fBusy ? 'Saving…' : 'Save Factor'}</button></div>
            {fError && <p className="rounded-xl bg-red-50 p-2 text-red-800 sm:col-span-3 font-semibold" role="alert">{fError}</p>}
          </form>
        ) : (
          <p className="mt-2 text-xs sm:text-sm text-gray-500">Only admins / kitchen managers can manage factors.</p>
        )}
      </div>

      <div className={card}>
        <h2 className="text-base font-bold text-[#0C2741]">Persisted Impact Snapshots ({snapshots.length})</h2>
        <p className="mt-1 text-xs sm:text-sm text-gray-500">Stored numbers make past reports reproducible — values plus the filters and method that produced them.</p>
        {snapshots.length === 0 ? <p className="mt-2 text-xs sm:text-sm text-gray-500">None yet. Build a report above, then persist it as a snapshot.</p> : (
          <div className="mt-3 overflow-x-auto custom-scrollbar">
            <table className="w-full text-xs sm:text-sm min-w-[600px]">
              <thead className="bg-[#F9FCFA] text-[#0C2741] font-semibold border-b border-[#E3ECE6]">
                <tr className="text-left">
                  <th className="py-2.5 px-3">Date</th>
                  <th className="py-2.5 px-3">Saved</th>
                  <th className="py-2.5 px-3">Cost (est.)</th>
                  <th className="py-2.5 px-3">CO2e (est.)</th>
                  <th className="py-2.5 px-3">Detail</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#E3ECE6]">
                {snapshots.map((s) => (
                  <tr key={s.id} className="hover:bg-[#F9FCFA] transition-colors">
                    <td className="py-2 px-3 font-medium text-[#0C2741]">{s.date.slice(0, 10)}</td>
                    <td className="py-2 px-3 font-bold text-[#006B48]">{s.foodSavedKg} kg</td>
                    <td className="py-2 px-3 font-semibold text-[#0C2741]">₹ {s.costSavedEstimate.toLocaleString()}</td>
                    <td className="py-2 px-3 text-[#006B48]">{s.co2AvoidedKgEstimate} kgCO2e</td>
                    <td className="py-2 px-3 max-w-xs truncate text-xs text-gray-500">{s.detail?.method ?? ''} {JSON.stringify(s.detail?.filters ?? {})}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
